### ISSUE TITLE
As a user who want help, I want to have access to different options of help so that I can be more specific with the issue

### ISSUE THREAD

**Issue by Chegemartinx** [Kukuza/kukuza-interface#49]
Success criteria:
When a user clicks help: SHould get the following options
1. FAQ's
2. Raise account send limit
3. Forum
4. Contacts

**Comment by Chegemartinx** [comment]
Do we need a forum option for now @steffenkrogmann seems like Valora have built it on webview for their community.

**Comment by steffenkrogmann** [comment]
FAQ's
Raise account send limit
Ask the Community
Documentation
Contact (singular)

@Chegemartinx
