### ISSUE TITLE
As a user who want more on Kukuza governance, I want to have a link to the website so that I can dig deeper

### ISSUE THREAD

**Issue by Chegemartinx** [Kukuza/kukuza-interface#72]
Acceptance criteria;
- After the last swipe screen, the user gets into a page where they can access a link to Kukuza website (governance section)

**Comment by Chegemartinx** [comment]
@steffenkrogmann not sure about where this could be placed on the app? In the drawer menu?

**Comment by steffenkrogmann** [comment]
Yes @Chegemartinx 

I suggest between "Earn" and "Settings"

**Comment by Chegemartinx** [comment]
@steffenkrogmann thanks
